name: synchronise repository labels

on: push

jobs:
  apply_labels:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: synchronize labels
        uses: julb/action-manage-label@v1
        with:
          from: https://raw.github.com/gliff-ai/.github/main/.github/labels.yml
          skip_delete: false
        env:
          GITHUB_TOKEN: ${{ secrets.ROBOT_PAT }}
